### ISSUE TITLE
[Bug]: Outdated full links

### ISSUE THREAD

**Issue by sof202** [ejh243/BrainFANS#110]
### What happened?

here is a list of files that are pointing to gpfs

general/processing/outputFileSizes
array/SNParray/utilitys/summarizeCNVCalls
integrative/chromHMM/processing/createAnnotationFiles.r
sequencing/ATACSeq/preprocessing/CreateFACS_SFARI_fetalSamplesDatalFileForDB.r
sequencing/DNAhydroxy/jobSubmission/peakCalling5hmCIncreasingSampleSizes.sh
sequencing/DNAhydroxy/preprocessing/QCSummary.rmd

Realistically, there should be no full or relative file paths anywhere for maximum portability.

**Comment by ejh243** [comment]
@ew367 could we archive these files as not clear how these fit into pipeline: 

sequencing/ATACSeq/preprocessing/CreateFACS_SFARI_fetalSamplesDatalFileForDB.r
general/processing/outputFileSizes

**Comment by ew367** [comment]
> @ew367 could we archive these files as not clear how these fit into pipeline:
> 
> sequencing/ATACSeq/preprocessing/CreateFACS_SFARI_fetalSamplesDatalFileForDB.r general/processing/outputFileSizes

@ejh243 they can be deleted
