### ISSUE TITLE
Normalisation script Cell.type vs Cell_Type[Bug]: 

### ISSUE THREAD

**Issue by AnthonyKl98** [ejh243/BrainFANS#135]
### What happened?

Script contains QCmetrics$Cell.type, however the standard name is Cell_Type. Running the script as it currently is, it normalised all my samples together rather than normalising the cell types separately. When loading in the normalised data, the object is called normbeta rather than celltypeNormbeta. Could cell.type be corrected to Cell_Type, or ensure it matches what is on your sample sheet so that it normalises the cell types separately and gives celltypeNormbeta?

**Comment by ejh243** [comment]
This is will partly be resolved by the script to check format of sample sheet (& config file). links to #32
