### ISSUE TITLE
Install libraries at start of QC[Bug]: 

### ISSUE THREAD

**Issue by rhaigh5** [ejh243/BrainFANS#145]
### What happened?

Current pipeline does not include the install.libraries script at the start of QC - if any packages are missing from other scripts the analysis breaks. Install.libraries also needs to be updated to include most recent QC scripts before incorporating

### How can the bug be reproduced?

Run pipeline with missing packages

**Comment by ejh243** [comment]
This is similar to #52

**Comment by rhaigh5** [comment]
I think all the packages are in the 137 bug script now but it might be good to incorporate it into the start of the pipeline just with a series of "if required" lines to avoid slowing it down if they're already installed

**Comment by ejh243** [comment]
Nice idea - can you make those edits?

**Comment by rhaigh5** [comment]
Yes will do - CETYGO is missing and I'll add any others as they come up. also the new version of R isn't working with bigmelon but 4.2.1 is fine so that's just something to highlight for the config
