### ISSUE TITLE
[Bug]: CountMTReads not generating properly, escape sequences not recognised

### ISSUE THREAD

**Issue by sof202** [ejh243/BrainFANS#157]
### What happened?

When running `sequencing/ATACSeq/preprocessing/countMTReads.sh`, the output file's header row will have literal character escape sequences. I presume this is not the desired effect considering the rest of the file is tab delimited.

### Relevant log output

```shell
$ head ./countMTReads.txt
Filename\tMTReads\tAllMappedReads\n
11031_EX161_NEUN_S1     1179779 165581552
```

**Comment by sof202** [comment]
R markdowns that reference this file skip the header row, which is probably why this hasn't been flagged. It still isn't the desired behaviour though (I hope).

**Comment by marinafloresp** [comment]
Would it be better to change the output to be a csv file instead of a txt file? So that is read as a table from the R markdowns

**Comment by sof202** [comment]
I don't think it will make a difference. The R markdown doesn't specify a delimiter, it just reads the file (so the delimiter will be inferred from the file's contents). Can do if you want
