### ISSUE TITLE
[Code Refactor]: .gitignore has lots of redundant lines

### ISSUE THREAD

**Issue by sof202** [ejh243/BrainFANS#17]
### Contact Details

s.o.fletcher@exeter.ac.uk

### Path to affected file

```shell
BrainFANS/.gitignore
```

### Type of refactor

Code optimisation

### Description of required code refactor

Currently the .gitignore file has many lines that are doing the same thing or doing nothing. 
For example:
Line 16: `JobSubmissionScripts/`

This folder doesn't exist in the repository, and thus does not need to be in this file.

**Comment by sof202** [comment]
Partially fixed with the introduction of the documentation website.
Remaining lines that have not been ruled out (due to not being required) are:
*.csv
*.pdf
sequencing/longReadseq/*

I'm keeping these lines in the .gitignore file for now. It would be nice if comments could be put above these lines explaining why these files are being ignored.
I suspect the main reason is to avoid uploading any analyses or results. If this is the case, the issue can be closed

**Comment by ejh243** [comment]
I think likely I am the only person who has added anything to this file and I can't recall a particular reason other than the one you mentioned. 

This would also be somewhat fixed by the intention to run scripts from the data directory.

**Comment by sof202** [comment]
Good to keep them in just in case. 
What about the `sequencing/longReadseq/*` line?

**Comment by ejh243** [comment]
That was for a case of someone putting scripts in the folder with no intention of commiting. An exception for a scenario that should no longer exist as we work on our own versions of the scripts.

**Comment by sof202** [comment]
I thought that might be the case. I will remove this line and the issue can be closed.
