### ISSUE TITLE
[Bug]: Possible bug in QC.rmd script in DNA microarray QC pipeline

### ISSUE THREAD

**Issue by dmsoanes** [ejh243/BrainFANS#179]
### Contact Details

d.m.soanes@exeter.ac.uk

### What happened?

Microarray data was not cell sorted
The first part of the QC pipeline seemed to work fine:
1: Column names were correct
2: raw.gds and rawNorm.gds files were produced
3: calcQCMetrics.r worked (files attached) - although there was a warning: Sentrix position model failed, skipping not sure if that is important
4: The markdown script QC.rmd failed - **SexMismatches.csv** and **PlotsWithinDNAmMismatches.pdf** files produced but contained no data.

### How can the bug be reproduced?

Uploaded config, output, log and sample sheet files - other files can be found at /lustre/projects/Research_Project-MRC190311/DNAm/Darren/OHSU_006PLT_JN
[config.r.txt](https://github.com/user-attachments/files/16730648/config.r.txt)
[config.txt](https://github.com/user-attachments/files/16730649/config.txt)
[PassQCStatusAllSamples.csv](https://github.com/user-attachments/files/16730650/PassQCStatusAllSamples.csv)
[QCDNAdata_2559367.err.txt](https://github.com/user-attachments/files/16730651/QCDNAdata_2559367.err.txt)
[QCDNAdata_2559367.log](https://github.com/user-attachments/files/16730652/QCDNAdata_2559367.log)
[QCMetricsPostSampleCheck.csv](https://github.com/user-attachments/files/16730653/QCMetricsPostSampleCheck.csv)

### Relevant log output

```shell
processing file: QC.rmd


processing file: ./rmarkdownChild/sexCheck.rmd
Error in `$<-.data.frame`:
! replacement has 94 rows, data has 96
Backtrace:
 1. base::`$<-`(`*tmp*`, predictedduplicates, value = `<chr>`)
 2. base::`$<-.data.frame`(`*tmp*`, predictedduplicates, value = `<chr>`)
Warning message:
In in_dir(input_dir(), expr) :
  You changed the working directory to /lustre/projects/Research_Project-MRC190311/DNAm/Darren/OHSU_006PLT_JN (probably via setwd()). It will be restored to /lustre/projects/Research_Project-MRC190311/DNAm/Darren/OHSU_006PLT_JN/original_scripts/BrainFANS/array/DNAm/preprocessing. See the Note section in ?knitr::knit

Quitting from lines 858-875 [findDuplicateSamplesPostQC] (QC.rmd)
Execution halted
```

**Comment by sof202** [comment]
Initial notes:

code section:
```R
passQC<-QCSum$Basename[as.logical(QCSum[,"passQCS2"])]

snpCor<-snpCor[passQC, passQC]

if(max(snpCor, na.rm = TRUE) > 0.8){
  	# pull out samples that are genetically identical
  	predictedduplicates<-vector(length = ncol(snpCor))
  	for(i in 1:ncol(snpCor)){
  	  predictedduplicates[i]<-paste(sort(names(which(snpCor[,i] > 0.8))), sep = "|", collapse = "|")
  	}
  } else {
	  predictedduplicates<-colnames(snpCor)
	} 

  QCmetrics$predictedduplicates<-predictedduplicates
```

The `max(snpCor)` for Darren's data gives 1, so the if statement is running. 

Clearly the problem is that the `predictedduplicates` should not be given the same length as `snpCor` as the next line uses a `which` on `snpCor` which can easily result in fewer than `ncol(snpCor)` values.

**Comment by sof202** [comment]
I do not however know what the intended form of preditctedduplicates is, so I am unsure how to proceed.

**Comment by sof202** [comment]
I do not know what the intention is behind this block. My guess is this:

You want to filter `snpCor` to only those that pass the QC. Then you want to use these to get predicted duplicates (those with a very high correlation). For all other rows, you would just want an empty string as there are no predicted duplicates.

**Comment by sof202** [comment]
Also this if statement
```R
if(max(snpCor, na.rm = TRUE) > 0.8){
...
}
```

will always run as `snpCor`'s diagonal is 1s. This conditional logic can be removed no?
