### ISSUE TITLE
[Enhancement suggestion]: Pfilter for probe removal

### ISSUE THREAD

**Issue by eld211** [ejh243/BrainFANS#192]
### Enhancement suggestion

Add pfilter step before the normalisation step in the normalisation script

**Comment by ejh243** [comment]
Decided to add filter in prior to normalisation.

**Comment by ejh243** [comment]
Decided not to filter cross hybridising and SNP probes as these lists are changed from time to time and may therefore require further manipulation post hoc. 

Instead we will 

1. maintain a folder of these 
2. print a statement post normalisation to remind analyst that this needs to be done.
