### ISSUE TITLE
[Bug]: miscalculating genetically unique individuals in the QC report

### ISSUE THREAD

**Issue by Molly-Endicott** [ejh243/BrainFANS#193]
### Contact Details

me460@exeter.ac.uk

### What happened?

When generating the QC.html, I think the table that is generated in section 3.1 under the heading "Genetically Identical Samples" is potentially miscalculating the number of genetically unique individuals. The second table that identifies the expected distribution from the sample sheet is as expected. However, I believe the first table is possibly miscalculating the number of unique individuals as this does not match what I expect in my cohort.
![Screenshot 2024-09-09 at 16 21 40](https://github.com/user-attachments/assets/2294f867-95ff-4e06-9879-8f9e004743da)

### How can the bug be reproduced?

The data I am using to generate the QC.html is not currently publicly available. However, please just let me know if I can provide any further information.

**Comment by ejh243** [comment]
Yep - I was just looking at this and I have worked out the problem. Will fix now.
