### ISSUE TITLE
[Bug]: Principal component analysis for autosomal probes

### ISSUE THREAD

**Issue by Molly-Endicott** [ejh243/BrainFANS#195]
### Contact Details

me460@exeter.ac.uk

### What happened?

When running the QC.html, I think the number of PCs identified which explained > 1% of the variance could be taken from the control probes rather than the autosomal probes. 

Section 2.8 of the QC report identified 7 PCs explaining > 1% variance in my data which matches the number displayed in section 2.6 for my control probes. Section 2.8 investigating autosomal probes highlights 7 in the text but proceeds to show 9 PCs on the variance explained plot and plot 9 histograms & scatter plots explaining > 1% variant. From the plots, I think the text should read as "9 PCs identified which explained > 1% of the variance" as I think the number 7 might be taken from the control probes?
![Screenshot 2024-09-10 at 10 59 25](https://github.com/user-attachments/assets/f51bfd2c-5249-4cc2-87d3-89fd0846793d)
![Screenshot 2024-09-10 at 11 00 12](https://github.com/user-attachments/assets/e911ff94-07b7-4044-868b-86c13f880e6f)
![Screenshot 2024-09-10 at 11 00 34](https://github.com/user-attachments/assets/ffde220c-c60a-441a-be06-3862b446209b)

### How can the bug be reproduced?

The data I am using to generate the QC.html is not currently publicly available. However, please just let me know if I can provide any further information.

**Comment by ew367** [comment]
In QC.rmd line 437:

`To identify and visually inspect potential outliers we performed principal component analysis on the autosomal probes. We identified `r length(which(ctrl.pca > 0.01))` PCs which explained > 1% of the variance and focused on these for characterisation.`

It looks like `r length(which(ctrl.pca > 0.01))` needs changing to `r length(which(ctrl.pca > 0.01)) here

**Comment by sof202** [comment]
Yep agree.
