### ISSUE TITLE
[Bug]: clusterCellTypes.r script doesn't work when phenotype info is not available

### ISSUE THREAD

**Issue by ew367** [ejh243/BrainFANS#198]
### What happened?

Line 165:166 of the clsuterCellTypes script defines columns to keep from QCmetrics dataframe. If the keepcols object is not longer than 1, line 167 creates a vector rather than a dataframe for object "uniqueIDs". Line 171 then cannot access "Individual_ID" by column name selection, as the uniqueIDs object has no columns.

### How can the bug be reproduced?

supply a samplesheet with no Age, Sex, Phenotype, Tissue.Centre columns

### Relevant log output

```shell
uniqueIDs$Individual_ID <- as.character(uniqueIDs$Individual_ID)
Error in uniqueIDs$Individual_ID :
  $ operator is invalid for atomic vectors
```

**Comment by sof202** [comment]
So do we want to force `uniqueIDs` to be a data frame with `as.data.frame` then?
