### ISSUE TITLE
[Code Refactor]: installLibraries.r script contains unecessary code

### ISSUE THREAD

**Issue by ew367** [ejh243/BrainFANS#199]
### Path to affected file

```shell
BrainFans/Array/DNAm/preprocessing/installLibraries.r
```

### Type of refactor

Code optimisation

### Description of required code refactor

Currently the file needs a data directory file path to be provided on the command line in order to run.
This is used in the script to load the config File, however none of the config file parameters are then used at any point in the script.

To ammend: remove lines 15:20 from installLibraries.r script and change 1_runDNAmQC script line 37 to remove $DATADIR arg

**Comment by sof202** [comment]
It does use the config file though right?

It installs different manifest files (from `BiocManager`) depending on the value of `arrayType`:

```R
if(arrayType=='450K'){
  #library(IlluminaHumanMethylationEPICanno.ilm10b4.hg19)
  BiocManager::install("IlluminaHumanMethylation450kanno.ilmn12.hg19")
  BiocManager::install("IlluminaHumanMethylation450kmanifest")
}
if(arrayType=='V1'){
  BiocManager::install("IlluminaHumanMethylationEPICanno.ilm10b2.hg19")
  BiocManager::install("IlluminaHumanMethylationEPICmanifest")
}
if(arrayType=='V2'){
	install("jokergoo/IlluminaHumanMethylationEPICv2manifest")
	install("jokergoo/IlluminaHumanMethylationEPICv2anno.20a1.hg38")

}
```

Then again, there is a potential issue here as `arrayType` isn't in the example config file:

```R
projectTitle<-"MRC Schizophrenia FANS samples"
processedBy<-"Complex Disease Epigenetic Group, University of Exeter Medical School"
arrayVersion<-"Illumina EPIC microarray"
tissueType<-"brain" # needs to be brain or blood to generate relevant cell composition estimates
cellSorted<-FALSE # turns off cell type clustering check
```

The only variable that is similar is `arrayVersion`.
