### ISSUE TITLE
[Code Refactor]: config.example.r file is missing "arrayType" variable parameter

### ISSUE THREAD

**Issue by ew367** [ejh243/BrainFANS#201]
### Path to affected file

```shell
array/DNAm/config/config.example.r
```

### Type of refactor

Code optimisation

### Description of required code refactor

add `arrayType<-V2` to exmaple file

**Comment by ew367** [comment]
This is also true for 'tissueType' which must be either 'blood' or 'brain' and could be included as part of the fix for ehancement suggestion #184 

An alternative route would be to write a seperate checkRconfigFile.r script that runs before anything else in the pipeline

**Comment by sof202** [comment]
That's fair. We were talking about a file to check that the config file is in the correct form before. Let's stick with that and see how things look first.
