### ISSUE TITLE
[Documentation Fault]: Build out documentation

### ISSUE THREAD

**Issue by sof202** [ejh243/BrainFANS#21]
### Fault type

Page removal required, New page required

### Please describe the fault in detail

The website has now been initially deployed, now pages need to be added to build out the documentation.

Pages needed are:
- How to contribute to the repository [done, just needs refactoring]
- How to contribute to the documentation
- How to run the website locally
- Landing pages for documentation and analyses pages

**Comment by ejh243** [comment]
To start with I think we should organise into two sections (i.e. tabs in the navigation bar)

1. Users (documentation for those that want to run the pipelines)
2. Developers

In the Developers section would be nice to have (in addition to what @sof202 suggested above)

- design principles
- Getting in familiar with GitHub (links to tutorials/guides etc)
- Coding/Script conventions 

In the Users section would be nice to have

- how to organise your data
- how to log issues/bugs
- how to get started 
- overview of what each pipeline does
