### ISSUE TITLE
[Enhancement suggestion]: update dasen to dasen.adj

### ISSUE THREAD

**Issue by ejh243** [ejh243/BrainFANS#210]
### Contact Details

e.j.hannon@exeter.ac.uk

### Enhancement suggestion

Change all occurrences of `dasen` to `dasen.adj`.

**Comment by sof202** [comment]
Is this different from `adjustedDasen`? 

We are using `adjustedDasen` at line 244 in `array/DNAm/preprocessing/calcQCMetrics.r`, but `dasen` otherwise it would seem.

```R
if(arrayType == "V2"){
  normbeta <- adjustedDasen(
    onetwo = manifest$Infinium_Design_Type,
    chr = manifest$CHR,
    mns = read.gdsn(methylated(gfile)),
    uns = read.gdsn(unmethylated(gfile)))
  add.gdsn(gfile, "normbeta", normbeta, replace = TRUE)
} else {
  dasen(gfile, node="normbeta")
  normbeta<-index.gdsn(gfile, "normbeta")[,]
}
```
