### ISSUE TITLE
[Enhancement suggestion]: Remove techVar and bioVar variables and replace with hardcoded Sentrix_ID and Sentrix_Position and optional project variables (projVar)

### ISSUE THREAD

**Issue by ew367** [ejh243/BrainFANS#216]
### Enhancement suggestion

Remove techVar and bioVar variables and replace with hardcoded Sentrix_ID and Sentrix_Position and optional project variables (projVar)

Sentrix_ID and Sentrix_Position will need to be included as plot variables in the QC report for all projects so should be hardcoded in to the QC.rmd script. There is also no need to distinguish between technical and biological variables so these can be combined into an overall (optional) project variable.

affected scripts:

config.example.r,  checkRconfigFile.r and QC.rmd files

**Comment by ew367** [comment]
This also address #188

**Comment by sof202** [comment]
Also addresses #33 I think
