### ISSUE TITLE
[Enhancement suggestion]: GitHub description

### ISSUE THREAD

**Issue by sof202** [ejh243/BrainFANS#225]
## Description

A quick description of the repository on GitHub would be nice for metadata reasons (it would also look nicer on the lab website this way).

![image](https://github.com/user-attachments/assets/dee34ace-b143-4ba5-b8a5-5a14fcde5270)

## Documentation

As a bonus we can put the documentation website here as well (Though there isn't any documentation on it just yet, so that can wait).

![image](https://github.com/user-attachments/assets/2719bda1-621a-4716-aee4-fa7839170023)

**Comment by sof202** [comment]
It could be something as simple as:

> Complex Disease Epigenomics Group's pipelines for DNA methylation arrays, SNP arrays, BS-Seq, ATAC-Seq and ChIP-Seq

**Comment by ejh243** [comment]
implemented
