### ISSUE TITLE
[Code Refactor]: create function to load and standardise manifests

### ISSUE THREAD

**Issue by ew367** [ejh243/BrainFANS#235]
### Path to affected files

- array/DNAm/preprocessing/calQCMetrics.r
- array/DNAm/preprocessing/clusterCellTypes.r
- array/DNAm/preprocessing/rmarkdownChild/ctCheck.rmd
- array/DNAm/preprocessing/normalisation.r
  - Though this code is currently commented out

### Type of refactor

Code optimisation

### Description of required code refactor

Many of the pipeline scripts contain identical code to load and standardise the manifest files for the different array versions. It would be nice to call a function that can be shared across files instead

**Comment by sof202** [comment]
@ejh243 
Could we add this to [cdegUtilities](https://github.com/EpigeneticsExeter/cdegUtilities)?

I don't think it is a good idea to have a file with this function loose in this repository. I'm sure it will become a nuisance at some point in the future. It also just reduces complexity to do it this way.

**Comment by sof202** [comment]
Added function to cdegUtilities.
