### ISSUE TITLE
[Bug]: Sex check fails on EPICV2

### ISSUE THREAD

**Issue by ejh243** [ejh243/BrainFANS#24]
### What happened?

The hard coded thresholds for deciding whether a sample is male or female causes only one sex to be predicted. This is a consequence of a change in the probes on the different versions of the array. 

These thresholds either need to be calculated more intelligently or array specific thresholds used. 

@ew367 Something to look at once your updates to pipeline are complete.

**Comment by ew367** [comment]
I've added it my to do list..

**Comment by ejh243** [comment]
Is thi complete @ew367?
