### ISSUE TITLE
[Code Refactor]: Run scripts from data folder rather than scripts folder

### ISSUE THREAD

**Issue by ejh243** [ejh243/BrainFANS#25]
### Path to affected file

```shell
Multiple files affected including: 
https://github.com/ejh243/BrainFANS/blob/master/array/DNAm/preprocessing/jobSubmission/1_runDNAmQC.sh
https://github.com/ejh243/BrainFANS/tree/master/array/SNPArray/jobSubmission/*
https://github.com/ejh243/BrainFANS/tree/master/sequencing/ATACSeq/jobSubmission/*
```

### Type of refactor

Code optimisation

### Description of required code refactor

Currently we submit scripts for execution from the scripts folder and provide a path to the relevant config files. Instead we want each data folder to have the relevant config files and execute scripts from there. Means we can have standardized config file names/paths that don't need to be explicitly specified.

Actions include:

- Config files will need a scripts path variable (this should be consistent across modalities)
- Changes to relevant READMEs to include how to create config file and where it should be located
- Changes to developers/user documentation for data management to include location of config file
- Changes to paths in any script that executes scripts, mainly job submission scripts or wrapper scripts. This will mainly be bash scripts but there may be others affected.

**Comment by sof202** [comment]
I'm presuming that in order to make scripts more reusable, the user will need to specify the full file path to the relevant config file (which would be to one of the data folders). This would be instead of just putting the path to the config file into the script itself. Am I correct in assuming this?

**Comment by sof202** [comment]
```bash
#SBATCH --output=jobname_%j.log # replace with %a %A if it's an array
#SBATCH --error=jobname_%j.err
#SBATCH --job-name=jobname

source $1 || 
  { >&2 echo "config file not found at $1"
  exit 1
  }

# SLURM moves your script so you can't use $0 to find the position
# of the script when running with sbatch
SCRIPT_PATH=$(scontrol show job "$SLURM_JOBID" | \
  awk '/Command=/{print $1}' | \
  cut -d= -f1)
SCRIPT_DIR=$(realpath "$(dirname "$SCRIPT_PATH")")

mkdir -p "$LOG_DIRECTORY" # Somewhere specified in config

# SLURM_JOB_ID === %j
# SLURM_ARRAY_JOB_ID === %A
# SLURM_ARRAY_TASK_ID === %a
mv "${SLURM_SUBMIT_DIR}/${SLURM_JOB_NAME}_${SLURM_JOB_ID}.log" \
  "${LOG_DIRECTORY}/${SLURM_JOB_NAME}_${SLURM_JOB_ID}.log"
mv "${SLURM_SUBMIT_DIR}/${SLURM_JOB_NAME}_${SLURM_JOB_ID}.err" \
  "${LOG_DIRECTORY}/${SLURM_JOB_NAME}_${SLURM_JOB_ID}.err"

```

**Comment by ejh243** [comment]
Ultimately we decided to enable the scripts to be submitted from any folder, by specifying the scripts folder in the config file.
