### ISSUE TITLE
[Enhancement suggestion]: create basic technical QC or 'full' QC options for running DNAm QC pipeline

### ISSUE THREAD

**Issue by ew367** [ejh243/BrainFANS#33]
### Enhancement suggestion

Have different options for running a quicker version of the QC or full version of the QC

**quicker technical only version**: intensities/bscon/PCA of control-probe intensities/detection p value/count number of missing values
e.g. for collaborators data we are not involved in analysing/initally checking that the experiment as worked
**outputs**: html QC report, csv file of QC metrics

**Full version:** run above and then additionally run: Horvaths epigenetic age/Cortical Clock Age/check effect of normalisation/predict sex/check duplicate samples using SNPs on array/compare to external snp data
**outputs:** as above, plus: updated gds file containing normalised beta values, QC rdata object containing QCmetrics, snpCor, betas.pca, ctrl.pca, pFOut, geno.mat, betas.rs, rsbetas, samplesPassFail csv file, html QC report

**Comment by ejh243** [comment]
Technical QC is effectively just stage 1 of the QC, i.e. no sexCheck, no genoCheck, no ctCheck. 

Could add variable to config file to specify technical QC only which would then override config specified parameters.

Also need to prevent execution of scripts post calc QC metrics.

Do we need a separate rmarkdown for this?

**Comment by sof202** [comment]
#216?

**Comment by ew367** [comment]
Yes, I think this address this issue
