### ISSUE TITLE
[Bug]: GDS object permisions

### ISSUE THREAD

**Issue by ejh243** [ejh243/BrainFANS#39]
### Contact Details

e.j.hannon@exeter.ac.uk

### What happened?

I can't load a gds object into R that has been created by someone else. I get Permission denied. We need to change the file permissions after creation. This might apply to some other elements of the QC too.

**Comment by ew367** [comment]
@ejh243 can this be done through the QC pipeline script? Or does it requre the user to manually change the permissions on the command line?

**Comment by ejh243** [comment]
Probably on the command line. But an alternative solution in some situations within in R will be to set the "readonly" argument to TRUE (if you only want to read the data not change it).

**Comment by ejh243** [comment]
@alicemfr I think this has been done?

**Comment by alicemfr** [comment]
Yes, in 1_runDNAmQC.sh the permissions are changed after creation of raw.gds and rawNorm.gds to 755 to each.
