### ISSUE TITLE
[Enhancement suggestion]: edit DNAm QC pipeline to work with blood data

### ISSUE THREAD

**Issue by ew367** [ejh243/BrainFANS#48]
### Enhancement suggestion

adapt the cluerCellType sections of the QC pipeline to work with blood data. e.g. run blood cell type deconvolution and make the brain cell type specific parts optional

**Comment by ejh243** [comment]
@ew367 are we happy that this is complete?

**Comment by ew367** [comment]
Yes @ejh243
