### ISSUE TITLE
[Enhancement suggestion]: add script to start of DNAm QC pipeline to check formating of config files and sample sheet

### ISSUE THREAD

**Issue by ew367** [ejh243/BrainFANS#50]
### Enhancement suggestion

config file: perform initial checks that all necessary parameters are defined, and conform to standardised input (e.g. arrayType is V1/V2/hm450k)

samplesheet: perform initial checks that columns contain valid and correctly formatted names

**Comment by ejh243** [comment]
By my reckoning these are the necessary checks - 

sampleSheet:

Chip.ID, Chip.Location, Sample_ID, Individual_ID (compulsory)
Genotype.IID, Age (optional)
Sex (compulsory if sexCheck == TRUE)
Cell_Type (compulsory if ctCheck = TRUE)

config file:
snpCheck, sexCheck, intenThres, nvThres, perMiss, ctCheck, tissueType, cellSorted

**Comment by alicemfr** [comment]
- [x] Script to check all required sampleSheet column names are present
- [ ] Script to check format of sampleSheet columns is correct
- [ ] Script to check all required config file parameters are present
- [ ] Script to check config parameters are formatted correctly
