### ISSUE TITLE
[Enhancement suggestion]: add script to ensure user has all R packages pre installed

### ISSUE THREAD

**Issue by ew367** [ejh243/BrainFANS#52]
### Enhancement suggestion

add script at the beginning that checks if user has the necessary R packages installed, and in the correct versions. If not, install them prior to running the QC pipeline

**Comment by ejh243** [comment]
@rhaigh5 has started this here: https://github.com/ejh243/BrainFANS/blob/master/array/DNAm/preprocessing/installLibraries.r

Is there anything missing?
