### ISSUE TITLE
[Bug]: load R functions package command does not work

### ISSUE THREAD

**Issue by ejh243** [ejh243/BrainFANS#60]
### Contact Details

e.j.hannon@exeter.ac.uk

### What happened?

When loading internal R library in [load GDS script](https://github.com/ejh243/BrainFANS/blob/master/array/DNAm/preprocessing/loadDataGDS.r) on line 37  (and possibly others) relative path no longer works. 

### How can the bug be reproduced?

`devtools::load_all(path = "../functionsR")`

**Comment by ejh243** [comment]
Also a question as to whether this package should be external to the pipeline - I think possibly so...

**Comment by SiyiSEA** [comment]
fixed
